# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cheatsheets
email: cheatsheets@spenser.io
description: > # this means to ignore newlines until "baseurl:"
  My cheatsheets
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: spenserpothier
github_username:  spenserpothier

exclude:
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
  - _deprecated


# Build settings
markdown: kramdown

category_names:
  - Amazon Web Services
  - Apps
  - Chef
  - Devops
  - Docker
  - Git
  - Ledger
  - Ruby
  - Vim

